"""Validate the golden rules corpus against the live engine.

The corpus (`tests/golden/positions.txt.gz`, generated by `tools/golden.py`) is
the oracle a re-implementation of the rules is checked against. For that to mean
anything, two properties have to hold here first:

* **It is faithful.** Every recorded move list, terminal flag and winner must
  still match what the live engine produces. If someone changes the rules, this
  fails — the same way `tests/test_perft.py` fails — but it names the position
  and the specific move that moved, rather than reporting a changed total.
* **It is diverse.** A corpus of ten thousand opening positions would pass every
  check and catch almost nothing. The coverage test pins the regimes that
  actually exercise the awkward rules: sparse endgames, terminals, stalemates,
  the 50-move boundary, captures and river jumps.

It also re-runs `assert_board_consistent` over every decoded position, which
exercises the grid / piece-index / Zobrist agreement across ten thousand
positions rather than the handful a hand-written test reaches.
"""

from __future__ import annotations

import pytest

from engine.move_generator import generate_legal_moves
from engine.pieces import Color
from tests.helpers import assert_board_consistent
from tools.golden import (
    CORPUS_PATH,
    EVALS_PATH,
    decode_board,
    decode_position,
    encode_board,
    encode_position,
    read,
)


@pytest.fixture(scope="module")
def corpus() -> list[str]:
    if not CORPUS_PATH.exists():
        pytest.fail(
            f"golden corpus missing at {CORPUS_PATH}; regenerate with "
            f"`python -m tools.golden`"
        )
    return read()


def test_corpus_is_present_and_populated(corpus):
    assert len(corpus) == 10_000


def test_every_line_round_trips(corpus):
    """decode -> encode must reproduce the line byte for byte."""
    for i, line in enumerate(corpus):
        gs, _, _, _ = decode_position(line)
        assert encode_position(gs) == line, f"line {i} did not round-trip"


def test_recorded_moves_match_live_generation(corpus):
    """The recorded legal moves must still be what the engine generates."""
    for i, line in enumerate(corpus):
        gs, _, _, recorded = decode_position(line)
        live = sorted(
            generate_legal_moves(gs.board, gs.turn),
            key=lambda m: (m.fc, m.fr, m.tc, m.tr, m.captured),
        )
        live_tuples = [(m.fc, m.fr, m.tc, m.tr, m.captured) for m in live]
        assert live_tuples == recorded, (
            f"line {i}: move generation diverged\n"
            f"  board   {line.split()[0]}\n"
            f"  missing {sorted(set(recorded) - set(live_tuples))}\n"
            f"  extra   {sorted(set(live_tuples) - set(recorded))}"
        )


def test_recorded_terminal_and_winner_match(corpus):
    """Terminality derived from the position must match what was recorded.

    This is the test that earns `tools.golden.derive_result`: the corpus cannot
    carry `GameState.result` (it is set by `apply_move`, not implied by a bare
    board), so decoding recomputes it positionally. If that recomputation were
    not equivalent, the ~1000 terminal positions here would say so.
    """
    for i, line in enumerate(corpus):
        gs, terminal, winner, _ = decode_position(line)
        assert gs.is_terminal() == terminal, f"line {i}: terminal flag diverged"
        live = gs.get_winner()
        live_char = "-" if live is None else ("B" if live == Color.BLUE else "K")
        assert live_char == winner, f"line {i}: winner diverged"


def test_every_decoded_board_is_self_consistent(corpus):
    """Grid, piece index and incremental Zobrist agree, 10k times over."""
    for i, line in enumerate(corpus):
        gs, _, _, _ = decode_position(line)
        try:
            assert_board_consistent(gs.board)
        except AssertionError as exc:  # pragma: no cover - only on a real failure
            raise AssertionError(f"line {i}: {exc}") from exc


def test_board_encoding_round_trips_for_the_start_position():
    from engine.game_state import GameState

    gs = GameState()
    gs.new_game()
    text = encode_board(gs.board)
    assert len(text) == 63
    assert decode_board(text).hash == gs.board.hash


def test_recorded_evaluations_are_not_stale(corpus):
    """The evaluation corpus must still match what the evaluator produces.

    Without this, changing an evaluation weight would leave `evals.txt.gz`
    describing an engine that no longer exists, and the Rust differential test
    would start failing against a stale oracle rather than reporting a real
    divergence. This is the check that says which side is wrong.
    """
    from ai.evaluator import evaluate
    from ai.search_config import strong_config

    if not EVALS_PATH.exists():
        pytest.fail(f"missing {EVALS_PATH}; regenerate with `python -m tools.golden`")

    cfg = strong_config()
    recorded = read(EVALS_PATH)
    assert len(recorded) == len(corpus), "evaluation corpus is out of step with positions"

    for i, (pos_line, eval_line) in enumerate(zip(corpus, recorded, strict=True)):
        board, stm, score = eval_line.split(" ")
        assert pos_line.startswith(f"{board} {stm} "), f"line {i}: corpora disagree on position"
        gs, _, _, _ = decode_position(pos_line)
        assert evaluate(gs, Color.BLUE, cfg) == int(score), (
            f"line {i}: recorded evaluation is stale for {board}"
        )


def test_corpus_covers_the_regimes_that_matter(corpus):
    """A corpus that lost its diversity would pass every other test here."""
    sparse = terminals = stalemates = at_fifty = 0
    captures = jumps = 0
    for line in corpus:
        gs, terminal, _, moves = decode_position(line)
        if sum(1 for ch in line.split()[0] if ch != ".") <= 4:
            sparse += 1
        if terminal:
            terminals += 1
        if not moves:
            stalemates += 1
        if gs._halfmove_clock >= 100:
            at_fifty += 1
        for fc, fr, tc, tr, cap in moves:
            if cap:
                captures += 1
            if abs(fc - tc) + abs(fr - tr) > 1:
                jumps += 1

    assert sparse >= 300, f"too few sparse endgame positions ({sparse})"
    assert terminals >= 300, f"too few terminal positions ({terminals})"
    assert stalemates >= 50, f"too few stalemates ({stalemates})"
    assert at_fifty >= 100, f"too few positions at the 50-move boundary ({at_fifty})"
    assert captures >= 500, f"too few capture moves ({captures})"
    assert jumps >= 500, f"too few river-jump moves ({jumps})"
